apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-scheduler
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-scheduler
  template:
    metadata:
      labels:
        app: gpu-scheduler
    spec:
      # TODO: debug RBAC later
      # serviceAccountName: gpu-scheduler
      # kubectl create serviceaccount k8sadmin -n kube-system; kubectl create clusterrolebinding k8sadmin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:k8sadmin
      serviceAccountName: k8sadmin
      terminationGracePeriodSeconds: 1
      containers:
      - name: gpu-scheduler
        image: gpu-scheduler:latest
        imagePullPolicy: Never
        # resources:
        #   limits:
        #     memory: 2Gi
        #   requests:
        #     memory: 128Mi
        #     cpu: "0.2"

