apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gpu-scheduler-check
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gpu-scheduler-check
  template:
    metadata:
      labels:
        app: gpu-scheduler-check
      annotations:
        gpu-scheduling-map: |
          0=node1:0,1
          1=node2:2
          2=node3:0,1,2
          3=node4:3
          4=node4:3
    spec:
      schedulerName: gpu-scheduler
      containers:
      - name: gpu-scheduler-check
        image: gpu-scheduler-check:latest
        imagePullPolicy: Never
        env:
        - name: CUDA_VISIBLE_DEVICES
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['cuda']
        # - name: TEST1
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.labels
        #  Unsupported value: "metadata.labels": supported values: "metadata.name", "metadata.namespace", "metadata.uid", "spec.nodeName", "spec.serviceAccountName", "status.hostIP", "status.hostIPs", "status.podIP", "status.podIPs"
        - name: TEST2
          valueFrom:
            fieldRef:
              fieldPath: metadata.name